@startuml
skinparam classAttributeIconSize 0
package Problems {
    class OptimizationProblem
    {
        +problem //has an internal optimization model using docplex
        +to_qp() //generates `QuadraticProgram` from problem infromation
        +is_feasible(x)
        +objective_value(x)
    }
    class GraphProblem
    {
        +__int__() //can create from ndarray and/or networkx
        +random_graph() //generates a random graph with n node
        +plot_graph(x) //visualize a solution on a graph.
    }

    class Clique
    {
        +size //need to set size K for a clique
    }

    class ExactCover
    {
    }

    class GraphPartinioning
    {

    }

    class KNapskac
    {

    }

    class MaxCut
    {

    }

    class SetProblem
    {
        +show_sets() //to show actual sets made from a bitstring. any good name?
    }

    class NumberPartitioning
    {

    }

    class SetPacking
    {

    }

    class StableSet
    {

    }

    class Tsp
    {
        +parse_tsplib_format() //reads graph in TSPLIB format from file.
    }

    class VehicleRouting
    {
    }

    class VertexCover
    {
    }

}

OptimizationProblem <|-- GraphProblem
OptimizationProblem <|-- SetProblem

GraphProblem <|-- Clique
GraphProblem <|-- GraphPartinioning
GraphProblem <|-- MaxCut
GraphProblem <|-- StableSet
GraphProblem <|-- Tsp
GraphProblem <|-- VehicleRouting
GraphProblem <|-- VertexCover

SetProblem<|-- ExactCover
SetProblem<|-- SetPacking
SetProblem <|-- NumberPartitioning
SetProblem <|-- KNapskac
@enduml

        -to_ising() //maybe we don't need this since we can convert a problem with converters